language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
sudo: false

matrix:
  allow_failures:
    - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); ENV["PYTHON"]=""; Pkg.add("Conda"); Pkg.build("PyCall"); using Conda; Conda.add("scipy"); Pkg.build("SndLib"); Pkg.test("SndLib"; coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("SndLib")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("SndLib")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
