language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.6
    - nightly
notifications:
    email: false
sudo: false

matrix:
  allow_failures:
    - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); ENV["PYTHON"]=""; Pkg.build("PyCall"); using Conda; Conda.add("scipy"); Pkg.build("SndLib"); Pkg.test("SndLib"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("SndLib")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
